AdvMasterDetails/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace AdvMasterDetails.Models
{

    [MetadataType(typeof(LoginCred))]
    public partial class Login
    {
        public string ConfirmPassword { get; set; }
    }
    public class LoginCred
    {
        [Display(Name = "Email ID")]
        [DataType(DataType.EmailAddress)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Email is Required")]
        public string Email { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is Required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Confirm Password and Password Do Not Match")]
        public string ConfirmPassword { get; set; }
        [Display(Name = "Remember Me")]
        public bool RememberMe { get; set; }
        [Display(Name = "Check For Admin Login")]
        public bool AdminType { get; set; }
    }

}

AdvMasterDetails/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdvMasterDetails.Models;
using System.Text;
using System.Data.Entity.Validation;
using System.Net.Mail;
using System.Net;
using System.IO;
using System.Security.Principal;
using System.Web.UI.WebControls;
using System.Web.UI;
using System.Web.Security;
using System.Threading.Tasks;

namespace AdvMasterDetails.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(AdvMasterDetails.Models.LoginCred login, string ReturnUrl = "")
        {
            bool Status = false;
            string message = "";
            using (InventoryDBEntities dc = new InventoryDBEntities())
            {
                if (IsEmailExist(login.Email))
                {
                    var v = dc.UserLogins.Where(a => a.Email == login.Email).FirstOrDefault();
                    if (v != null)
                    {
                        if (string.Compare(System.Web.Helpers.Crypto.Hash(login.Password), v.Password) == 0)
                        {
                            int timeout = login.RememberMe ? 525600 : 20;// 525600 minute = 1 year here timeout time is 20 min
                            var ticket = new FormsAuthenticationTicket(login.Email, login.RememberMe, timeout);
                            string encrypted = FormsAuthentication.Encrypt(ticket);
                            var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encrypted);
                            cookie.Expires = DateTime.Now.AddMinutes(timeout);
                            cookie.HttpOnly = true;
                            Response.Cookies.Add(cookie);
                            if (v.AdminType == true)
                            {
                                Status = true;
                                // return 
                                message = "Successfully Login";
                                return RedirectToAction("AprrovedOrder", "Home");
                            }
                            else if (Url.IsLocalUrl(ReturnUrl))
                            {
                                message = "Redirect To Home";
                                return Redirect(ReturnUrl);
                            }
                        }
                        else
                        {
                            Status = false;
                            message = "Invalid Credential Provided ";
                        }

                    }
                    else
                    {
                        message = "Invalid Credential Provided ";
                    }
                }
                else
                {
                        message = "Invalid Credential Provided ";
                }
            }
            ViewBag.Status = Status;
            ViewBag.Message = message;
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "Login");
        }

        [HttpGet]
        public ActionResult AdminReg()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdminReg([Bind(Exclude = "AdminType")]AdvMasterDetails.UserLogin user)
        {
            bool Status = false;
            string message = "";
            //Model Validation
            if (ModelState.IsValid)
            {

                #region //Email is already Exist Check
                var isExist = IsEmailExist(user.Email);
                if (isExist)
                {
                    ModelState.AddModelError("EmailExist", "Email is already Exist");
                    return View(user);
                }
                // user.UserID = user.UserID;
                #endregion
                #region Generate Activation Code
                //user. = Guid.NewGuid();
                #endregion
                #region Password Hashing
                user.Password = System.Web.Helpers.Crypto.Hash(user.Password);
                user.SecretKey = Guid.NewGuid();
                #endregion
                #region Save Data to Database
                using (InventoryDBEntities dc = new InventoryDBEntities())
                {
                    dc.UserLogins.Add(user);
                    try
                    {
                        dc.SaveChanges();
                        message = "Registration is successfully done. Account activation link " +
                            " has been sent to your email id : " + user.Email;
                        Status = true;

                    }
                    catch (DbEntityValidationException ex)
                    {
                        StringBuilder sb = new StringBuilder();
                        foreach (var eve in ex.EntityValidationErrors)
                        {
                            sb.AppendLine(string.Format("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                                                            eve.Entry.Entity.GetType().Name,
                                                            eve.Entry.State));
                            foreach (var ve in eve.ValidationErrors)
                            {
                                sb.AppendLine(string.Format("- Property: \"{0}\", Error: \"{1}\"",
                                                            ve.PropertyName,
                                                            ve.ErrorMessage));
                            }
                        }
                        message = "Error Message  :" + ex;
                    }
                    //Send Email to Users
                    // return RedirectToAction("Registration", "User");

                }
                #endregion

            }
            else
            {
                message = "Invalid Request";
            }

            ViewBag.Message = message;
            ViewBag.Status = Status;
            return View();
        }


        [NonAction]
        public bool IsEmailExist(string emailID)
        {
            using (InventoryDBEntities de = new InventoryDBEntities())
            {
                var EC = de.UserLogins.Where(a => a.Email == emailID).FirstOrDefault();
                return EC != null;// if not equal to null means True
            }
        }
    }
}

AdvMasterDetails/Controllers/PassResetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdvMasterDetails.Models;
using System.Net.Mail;
using System.Net;
using System.Web.Security;
using System.Threading.Tasks;
using System.Text.RegularExpressions;
using System.Data.Entity.Validation;

namespace AdvMasterDetails.Controllers
{
    public class PassResetController : Controller
    {
        // GET: PassReset
        [HttpGet]
        public ActionResult Forget()
        {
            return View();
        }


        [NonAction]
        public bool IsEmailExist(string emailID)
        {
            using (InventoryDBEntities de = new InventoryDBEntities())
            {
                var EC = de.UserLogins.Where(a => a.Email == emailID).FirstOrDefault();
                return EC != null;// if not equal to null means True
            }
        }
        [HttpGet]
        public ActionResult ForgetPassChange(string id)
        {
            bool Status = false;
            string message = "";
            try
            {
                using (InventoryDBEntities dc = new InventoryDBEntities())
                {
                    dc.Configuration.ValidateOnSaveEnabled = false; // Avoid Confirmation password does not match on save changes
                    var v = dc.UserLogins.Where(a => a.GlobalID == new Guid(id)).FirstOrDefault();
                    if (v != null)
                    {
                        v.AdminType = true;
                        var changepass = v.Password;
                        v.Password = rnd.Next(0003000, 99999999).ToString();
                        v.GlobalID = Guid.NewGuid();
                        dc.SaveChanges();
                        SendChangePassword(v.Email, v.GlobalID.ToString(), v.Password);
                        Status = true;
                        message = "Succefully Change Your Password";
                    }
                    else
                    {
                        message = "Invalid Request";
                        Status = false;
                    }

                }
            }
            catch (Exception)
            {

                message = "Invalid Request";
                Status = false;
            }
            ViewBag.Message = message;
            ViewBag.Status = Status;
            return RedirectToAction("Login", "Login");
        }

        Random rnd = new Random();
        [HttpPost]
        public ActionResult Forget(LoginCred user, string emailID, string activationcode, string oldpass)
        {
            bool Status = false;
            string message = "";
            if (!ModelState.IsValid)
            {

                emailID = user.Email;

                Random rnd = new Random();
                #region //Email is already Exist Check
                var isExist = IsEmailExist(user.Email);
                if (isExist)
                {
                    using (InventoryDBEntities dc = new InventoryDBEntities())
                    {
                        dc.Configuration.ValidateOnSaveEnabled = false;
                        var EC = dc.UserLogins.Where(a => a.Email == emailID).FirstOrDefault();

                        if (EC != null)
                        {
                            try
                            {
                                EC.GlobalID = Guid.NewGuid();
                                dc.SaveChanges();
                                ForgetPassChange(EC.GlobalID.ToString());
                                message = "Forget Password Link has been successfully Sent To your Email Account Please Check Your Email Account:  " + user.Email;
                                Status = true;
                            }
                            catch (Exception ex)
                            {

                            }
                        }
                        else
                        {
                            message = "Invalid Request";
                            Status = false;
                        }
                        //Send Email to Users
                        return RedirectToAction("Login", "Login");

                    }
                }

            }
            return View();
        }

        [HttpGet]
        public ActionResult ChangePassword(string id)
        {
            ViewBag.Status = false;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(AdvMasterDetails.Models.LoginCred user, string emailID, string activationcode, string oldpass, string id)
        {
            bool status = false;
            string message = "";
            using (InventoryDBEntities dc = new InventoryDBEntities())
            {
                dc.Configuration.ValidateOnSaveEnabled = false;// Avoid Confirmation password does not match on save changes
                try
                {
                    var v = dc.UserLogins.Where(a => a.GlobalID == new Guid(id)).FirstOrDefault();
                    if (v != null)
                    {
                        var changePass = user.Password;
                        changePass = System.Web.Helpers.Crypto.Hash(user.Password);
                        v.GlobalID = Guid.NewGuid();
                        v.Password = changePass;
                        dc.SaveChanges();
                        status = true;
                        message = "Your Account Password is changed and your password has been sent to your registered Email address.Please Check your email id for updated new password .";
                        SendChangePassword(v.Email, "", user.Password.ToString());
                    }
                    else
                    {
                        message = "Invalid Request";
                        status = false;
                    }

                }
                catch (Exception)
                {

                    message = "Invalid Request";
                    status = false;

                }
            }
            ViewBag.Message = message;
            ViewBag.Status = status;
            return View();

        }
        string sendText;
        [NonAction]
        public void SendChangePassword(string emailID, string activationcode, string userpass)
        {
            var verifyUrl = "/PassReset/ChangePassword/" + activationcode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);
            var fromEmail = new MailAddress("saurabh@promaxevents.in", "🔴 Promax Password");
            var toEmail = new MailAddress(emailID);
            var fromEmailPassword = "Kashyap007";
            string subject = "🔴 Promax Account Password 🔴";

            if ((userpass != "") && (userpass.Length >= 8))
            {
                sendText = "<br/><br/>Your Promax Account Password is : <b style='font-size:16px;color:#212121'>" + userpass + "</b><br/><br/>Your Click Here For Set Own New Password : " + link;
            }
            else
            {
                sendText = "<br/><br/>Your New Password is : " + userpass;
            }
            string body = sendText.ToString();
            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)

            };

            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                smtp.Send(message);

        }
    }

}
#endregion

AdvMasterDetails/Views/Login/AdminReg.cshtml
@model AdvMasterDetails.Models.Login

@{
    ViewBag.Title = "AdminReg";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .thick-green-border {
        border-color: darkgrey;
        border-width: 2px;
        border-style: solid;
        border-radius: 50%;
    }

    .smaller-image {
        width: 100px;
    }
    .btn-pink {background-color: #ef4f85; border-color: #ef4f85; color: #fff; font-weight: 500; text-transform: uppercase;}
</style>
<div class="header-foot">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 freeHead_section emailVerification">
                <div class="panel panel-default">
                    <div class="panel-body">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="page-head-title wow fadeInDown" style="visibility: visible; animation-name: fadeInDown;">
                                <img class="smaller-image thick-green-border" style="background-color:black;" src="~/Content/img/PromaxLogo_64.png" alt="Promax_logo"><hr />
                                <div class="title-area">
                                    <h2 class="title">ADMIN REGISTER<span> HERE</span></h2>
                                </div><hr />

                                <div class="head-content">

                                    <div class="form-group" style="">

                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email Id" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })<br />
                                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @placeholder = "Password" } })
                                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" value="Register" class="btn btn-sm btn-pink" />
                                        <a href="@Url.Action("","Home")" title="Back to home"><i class="glyphicon glyphicon-arrow-left"></i> Back to home</a>
                                    </div>

                                </div>

                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AdvMasterDetails/Views/Login/Login.cshtml
@model AdvMasterDetails.Models.LoginCred

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .thick-green-border {
        border-color: darkgrey;
        border-width: 2px;
        border-style: solid;
        border-radius: 50%;
    }

    .smaller-image {
        width: 100px;
    }
    .btn-pink {background-color: #ef4f85; border-color: #ef4f85; color: #fff; font-weight: 500; text-transform: uppercase;}
</style>
<div class="header-foot">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 freeHead_section emailVerification">
                <div class="panel panel-default">
                    <div class="panel-body">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="page-head-title wow fadeInDown" style="visibility: visible; animation-name: fadeInDown;">
                                <img class="smaller-image thick-green-border" style="background-color:black;" src="~/Content/img/PromaxLogo_64.png" alt="Promax_logo"><hr />
                                <div class="title-area">
                                    <h2 class="title" style="margin-bottom:30px;">ADMIN<span> LOGIN</span></h2>
                                </div><hr />

                                <div class="head-content">

                                    <div class="form-group">

                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email Id" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })<br />
                                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @placeholder = "Password" } })
                                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        <div class="col-sm-6">
                                            <input type="submit" value="Login" class="btn btn-pink" />
                                        </div>
                                        <div class="col-sm-6" style="margin-top:25px;">
                                            <a href="@Url.Action("Forget","PassReset")">Forget your Password ?</a>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                       <div class="col-sm-12">
                                           <a href="@Url.Action("Login","Login")" title="Back to Login"><i class="glyphicon glyphicon-arrow-left"></i> Back to home</a>
                                       </div>
                                    </div>
                                </div>

                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}